import SwiftUI

/// Global type scale.
///
/// The point sizes were ported 1:1 from Android's `sp` values, which read noticeably
/// smaller on iOS. Every `Font` in the app goes through `Font.app(_:weight:)` so the
/// whole UI can be scaled from this single constant instead of hand-editing ~140
/// literals — and so the ratios between headings, labels and values stay intact.
enum Typography {
    static let scale: CGFloat = 1.04
}

extension Font {
    static func app(_ size: CGFloat, weight: Font.Weight = .regular) -> Font {
        .system(size: size * Typography.scale, weight: weight)
    }
}

extension Color {
    /// Builds a colour from a 0xRRGGBB literal so Android hex constants can be
    /// ported over verbatim without hand-converting to floating point channels.
    init(hex: UInt32) {
        self.init(
            red: Double((hex >> 16) & 0xFF) / 255.0,
            green: Double((hex >> 8) & 0xFF) / 255.0,
            blue: Double(hex & 0xFF) / 255.0
        )
    }

    static let navyDark = Color(red: 0.012, green: 0.086, blue: 0.153)
    static let navyPrimary = Color(red: 0.059, green: 0.173, blue: 0.349)
    static let navyMedium = Color(red: 0.118, green: 0.227, blue: 0.541)
    static let blueAccent = Color(red: 0.008, green: 0.518, blue: 0.780)
    static let slateLight = Color(red: 0.945, green: 0.961, blue: 0.976)
    static let slateBorder = Color(red: 0.886, green: 0.910, blue: 0.941)
    static let slateTextDark = Color(red: 0.059, green: 0.090, blue: 0.165)
    static let slateTextLight = Color(red: 0.392, green: 0.455, blue: 0.545)
    static let slateMuted = Color(red: 0.580, green: 0.639, blue: 0.722)
    static let slate50 = Color(red: 0.973, green: 0.980, blue: 0.988)
    static let successGreen = Color(red: 0.086, green: 0.639, blue: 0.290)
    static let successGreenBg = Color(red: 0.863, green: 0.988, blue: 0.906)
    static let alertGold = Color(red: 0.851, green: 0.467, blue: 0.024)
    static let alertGoldBg = Color(red: 0.996, green: 0.953, blue: 0.780)
    static let dangerRed = Color(red: 0.863, green: 0.149, blue: 0.149)
    static let dangerRedBg = Color(red: 0.996, green: 0.886, blue: 0.886)
    static let orange50 = Color(red: 1.000, green: 0.969, blue: 0.929)
    static let orange100 = Color(red: 1.000, green: 0.929, blue: 0.835)
    static let orange800 = Color(red: 0.604, green: 0.204, blue: 0.071)
}

enum Copy {
    static func t(_ key: String, _ language: AppLanguage) -> String {
        let en: [String: String] = [
            "headerTitle": "TAX PULSE",
            "byHaddad": "by Haddad Audit Firm",
            "subtitle": "Lebanese Regulatory Payroll & Tax Engine",
            "activeService": "Active Service",
            "changeService": "Change Service",
            "payroll": "Payroll Tax",
            "payrollFull": "Payroll Tax",
            "payrollIntroTitle": "Payroll Tax Calculator",
            "payrollIntroBody": "This tool calculates tax liabilities on employment income, family allowances, and social security contributions. The calculations are based on the latest updated applicable laws, in accordance with official Lebanese tax brackets and Budget Law regulations.",
            "profit": "Tax on Profit",
            "profitIntroTitle": "Tax on Profits Calculator",
            "profitIntroBody": "This tool calculates income and profit tax liabilities for sole proprietorships and corporate entities. The calculations are based on the latest updated applicable laws, under either the real-profit or lump-sum legal systems with official progressive brackets.",
            "penalties": "Tax Penalties",
            "extensions": "Extensions",
            "reset": "Reset",
            "currency": "Salary Currency Designation",
            "selectCurrency": "Select Currency",
            "lbp": "Lebanese Pound (LBP)",
            "usd": "US Dollar (USD)",
            "salaryPeriod": "Salary Period",
            "monthly": "Monthly",
            "annual": "Annual",
            "basicSalaryLbp": "Basic Monthly Gross Salary (LBP)",
            "annualSalaryLbp": "Annual Gross Salary LBP",
            "monthlyUsd": "Monthly Dollars Salary (USD)",
            "annualSalaryUsd": "Annual Gross Salary USD",
            "enterSalary": "Enter salary numbers...",
            "enterMonthlySalary": "Enter current monthly salary...",
            "enterAnnualSalary": "Enter current annual salary...",
            "enterExchangeRate": "Enter custom exchange rate...",
            "currentValue": "Current Value:",
            "customRate": "Custom Dollar Exchange Rate (LBP/USD)",
            "useStandardRate": "Use Standard Rate: 89,500",
            "equivalentLbp": "Equivalent LBP Gross:",
            "marital": "Family Marital Status",
            "single": "Single",
            "spouseWorks": "Wife / Husband Works",
            "spouseDependent": "Wife / Husband Don't Work",
            "divorced": "Divorced",
            "widowed": "Widowed",
            "children": "Number of Children",
            "childrenMax": "Eligible up to max 5 children",
            "nssfReg": "Subject To NSSF Law",
            "familyRebates": "Family Rebates",
            "familyRebatesSub": "Apply Family Rebates (Self + Wife/Husband + Children)",
            "annualNssfCeiling": "Annual NSSF Ceiling (Optional)",
            "annualSicknessCeiling": "Annual Sickness Ceiling Override",
            "annualFamilyCeiling": "Annual Family Ceiling Override",
            "optional": "Optional",
            "calculate": "Calculate",
            "netTakeHome": "NET TAKE-HOME SALARY",
            "complianceSummary": "Payroll Compliance Summary",
            "netWithFamily": "NET TO BE CASHED",
            "basedOnEmployee": "Based on the employee's details",
            "baseMonthly": "Monthly Basic Salary",
            "annualGrossSalary": "Annual Gross Salary",
            "grossSalary": "Gross Salary",
            "sicknessNssf": "Sickness NSSF (3% Employee)",
            "mofTax": "MOF Progressive Tax",
            "familyAllowances": "Family Allowances Added",
            "taxableSalaryAfterRebates": "Taxable Salary After Rebates",
            "totalFamilyRebates": "Total Family Rebates",
            "nssfBranches": "NSSF Branches & Contributions (LBP)",
            "sicknessBranch": "Sickness & Maternity (11%)",
            "familyBranch": "Family Allowances (6%)",
            "endServiceBranch": "3. End of Service (8.5%)",
            "subjectBase": "Subject Base:",
            "ceilingLimit": "Ceiling Limit:",
            "fullWageNoCeiling": "Full Wage (No Ceiling)",
            "employeeContribution": "Employee Contribution",
            "employerContribution": "Employer Contribution",
            "totalNssfEmployer": "Total NSSF Employer (22.5%)",
            "employerCostBreakdown": "Employer & Corporate Cost Breakdown",
            "lessFamilyAllowances": "Less: Family Allowances Added",
            "totalCorpCost": "Total Corporate Cost",
            "warningCount": "1 Compliance Warning Detected",
            "warningDesc": "The base salary is below the legal Lebanese minimum wage rate of %@ for this period.",
            "secureCount": "0 Compliance Errors Found",
            "secureDesc": "This calculation conforms perfectly to standard Lebanese Ministry of Finance (MOF) & NSSF wage rules.",
            "readyTitle": "Ready for Tax Calculation",
            "readyDesc": "Enter salary to see detailed Lebanese tax & NSSF breakdown.",
            "mofActive": "MOF Active",
            "annualNetProfit": "Annual Net Taxable Profit",
            "enterAnnualNetProfit": "Enter annual taxable profit...",
            "calculateProfit": "CALCULATE PROFIT TAX",
            "profitSummary": "Profit Tax Assessment Summary",
            "profitDisclaimer": "Calculated automatically as per Lebanese Ministry of Finance progressive tables.",
            "totalTaxDue": "Total Profit Tax Due",
            "remainingNetProfit": "Remaining Net Profit (After Tax)",
            "rebateHimself": "Personal Rebate (Himself)",
            "rebateWife": "Wife / Husband Rebate",
            "spouseStatusDependent": "Does Not Work",
            "spouseStatusWorks": "Works",
            "rebateChildren": "Children Rebate",
            "taxableProfitAfterRebates": "Net Taxable Profit After Rebates",
            "totalAnnualDeductibleRebate": "Total Annual Deductible Rebate",
            "profitBracketsDetail": "Progressive Bracket Allocation Details",
            "splitWarning": "Split warning: 50% of children rebate is shared because wife/husband works",
            "penaltiesIntroTitle": "Tax Penalties Engine",
            "penaltiesIntroBody": "This tool calculates late filing verification fines and late payment collection fines for all major tax categories (payroll, profit, and VAT) when legal filing and settlement deadlines are exceeded.",
            "payrollTax": "Payroll Tax",
            "vatPenalties": "VAT Penalties",
            "taxAmount": "Tax Amount (LBP)",
            "enterTaxAmount": "Enter tax amount...",
            "zeroTaxNote": "Note: If there is no tax, you need to type zero to properly calculate the minimum declaration delay penalty.",
            "currentValueLower": "Current value:",
            "day": "Day",
            "month": "Month",
            "year": "Year",
            "profitDueYear": "Profit Due Year",
            "paymentDate": "Payment Date",
            "standardDueDate": "Standard system statutory due date: %@ (Click to prefill)",
            "calculatePenalties": "CALCULATE PENALTIES",
            "totalAmountDue": "Total Amount Due",
            "lateMonthsCounted": "%@ late month(s) counted",
            "minimumVerificationFine": "Minimum Compliance Penalty",
            "verificationFine": "Compliance Penalty",
            "collectionFine": "Collection Penalty",
            "r5PrincipalTaxPaymentStatus": "R5 Principal Tax Payment Status",
            "r5TaxPaidDescription": "Tax is paid. Collection penalty (3% monthly) applies strictly on the compliance penalty only (excluding principal tax). Even if tax is paid, enter the tax amount above to ensure accurate calculation.",
            "r5TaxUnpaidDescription": "Tax is not paid. The existing calculation applies the collection penalty to the principal tax and compliance penalty.",
            "extensionsIntroTitle": "MOF Deadline Extensions Tracker",
            "extensionsIntroBody": "This tool enables you to monitor regulatory extension decisions issued by the Lebanese Ministry of Finance (MOF) and save them permanently.",
            "selectExtensionTaxType": "Select Tax Type for Extension Tracking:",
            "vat": "VAT",
            "auditReport": "Audit Report",
            "fiscalYear": "Fiscal Year:",
            "filingQuarter": "Filing Quarter:",
            "primaryStatutoryDueDate": "Primary Statutory Due Date:",
            "originalDueDate": "Original due date before extensions",
            "officialExtendedDate": "Official Extended Due Date (Specify extension details):",
            "saveExtension": "Save Official Extension Date",
            "retrieveExtensions": "Retrieve Registered MOF Extensions",
            "retrieveExtensionsBody": "Click this button to query and display the most recently saved tax deadline extension configurations.",
            "retrieveNow": "Instantly Retrieve & Display",
            "retrievedRecord": "Retrieved Database Record:",
            "noExtensions": "No registered deadline extensions found yet.",
            "companyCategoryProfit": "Corporate/Taxpayer Entity Category:",
            "companyCategoryAudit": "Entity Category for Audit Report:",
            "contact": "Developed by Haddad Audit Firm",
            "contactSub": "Certified Auditors and Tax Advisors",
            "taxTypeLabel": "Tax Type",
            "companyTaxpayerType": "Company / Taxpayer Type",
            "companySal": "SAL Corporation",
            "companySarl": "SARL (LLC)",
            "companyPartnership": "Partnership",
            "companyIndividual": "Individual Enterprise",
            "companyExempt": "Exempt Institution",
            "companyOther": "Other Taxpayers",
            "minPrefix": "Min: %@ LBP",
            "corporateNote": "Important Corporate/Partnership Note: The penalty for failing to submit the statutory auditor's report is the same as the penalty for failing to submit the corporate/partnership income tax return. Therefore, please specify the final deadline for submitting the auditor's report, including the extended date, so that the penalty for non-submission remains identical to the penalty for failing to file the tax return.",
            "fiscalPenaltyAssessment": "Fiscal Penalty Assessment",
            "legalDueDateRow": "Legal Due Date:",
            "actualPaymentDateRow": "Actual Payment Date:",
            "totalDelayPeriod": "Total Delay Period:",
            "monthsSuffix": "Months",
            "delayExplain": "Timeline starts %@ to %@. Every fraction of a month passed strictly counts as a full month.",
            "noDelayExplain": "Calculations confirm payment within standard legal deadlines. No fines are incurred.",
            "principalTaxAmount": "1. Principal Tax Amount:",
            "verificationFineMinimum": "Verification Fine (Minimum):",
            "verificationFine5": "Verification Fine (5% monthly):",
            "verificationFine10": "Verification Fine (10% monthly):",
            "collectionFine3": "Collection Fine (3% monthly):",
            "collectionFine2": "Collection Fine (2% monthly):",
            "grandTotalToRepay": "GRAND TOTAL TO REPAY:",
            "principalPlusFines": "(Principal + Fines)",
            "compliancePenaltyWarning": "Compliance warning: Delay penalties are dynamically structured according to the statutory direct profit and payroll fiscal codes of the Lebanese Republic.",
            "calculatePenaltiesBtn": "CALCULATE PENALTIES",
            "calculatePayrollTaxes": "CALCULATE PAYROLL TAXES",
            "calculateProfitTaxBtn": "CALCULATE PROFIT TAX",
            "annualNssfNote": "Annual NSSF Note: The annual ceiling applied for the Family Allowance and Sickness & Maternity branches is the monthly ceiling multiplied by 12. In case of any changes or adjustments to the ceilings during the fiscal year, fill the above ceiling manually.",
            "putRateWarning": "\u{26A0}\u{FE0F} Put the dollar rate to proceed!",
            "contactHeading": "Haddad Audit Firm - Contact Details",
            "familyBranchNumbered": "2. Family Allowances (6%)",
            "subjectBaseSickness": "Subject Base:",
            "ceilingSickness": "Ceiling Limit:",
            "empContrib3": "Employee Contribution (3%):",
            "emprContrib8": "Employer Contribution (8%):",
            "subjectBaseFamily": "Subject Base:",
            "ceilingFamily": "Ceiling Limit:",
            "empContrib0": "Employee Contribution (0%):",
            "emprContrib6": "Employer Contribution (6%):",
            "minFloorZero": "Minimum Floor Alert: The entered tax is 0 LBP, which is below the category floor of %@. The minimum floor replaces the verification fine in full, and the collection fine applies on the verification fine (minimum floor).",
            "minFloorBelow": "Minimum Floor Alert: The entered tax is below the category floor of %@. The minimum floor replaces the verification fine in full, while the collection fine is calculated on the original tax amount plus the verification fine.",
            "minFloorCalc": "Minimum Floor Alert: The calculated verification fine is below the category minimum of %@. The minimum floor replaces the verification fine in full, while the collection fine is calculated on the original tax amount plus the verification fine.",
            "capAlert": "100% Verification Cap Active: The verification fine has exceeded the tax principal and was capped at exactly %@. The collection fine remains uncapped.",
            "emprContrib85": "Employer Contribution (8.5%):",
            "payrollCalculateShort": "Calculate",
            "payrollPlaceholderInfo": "Please press the \"Calculate\" button above to generate detailed tax, payroll, and social security contribution reports.",
            "approxUsdEquivalent": "≈ $%@ USD",
            "yearRestrictionTitle": "Year Restriction Alert",
            "yearRestrictionMessage": "You cannot go back to a year before 2024. Please start with 2024 or later.",
            "ok": "OK",
            "extensionSavedTitle": "Saved Successfully",
            "extensionSavedMessage": "The official extension date was successfully saved in the local database.",
            "extensionSameDateTitle": "Warning: Date Matches",
            "extensionSameDateMessage": "The entered extension date matches the base statutory due date (%@). Do you want to continue and save it anyway?",
            "cancel": "Cancel",
            "saveAnyway": "Save"
        ]
        let ar: [String: String] = [
            "headerTitle": "TAX PULSE",
            "byHaddad": "بواسطة شركة حداد لتدقيق الحسابات",
            "subtitle": "محرك الرواتب والامتثال الضريبي اللبناني",
            "activeService": "الخدمة النشطة",
            "changeService": "تغيير الخدمة",
            "payroll": "ضريبة الرواتب",
            "payrollFull": "ضريبة الرواتب والأجور",
            "payrollIntroTitle": "حاسبة ضريبة الرواتب والأجور",
            "payrollIntroBody": "تتيح لك هذه الأداة احتساب ضريبة الرواتب والأجور والتعويضات العائلية واشتراكات الضمان الاجتماعي. تجري الحسابات بناءً على أحدث القوانين النافذة والمحدثة، بالتوافق المباشر مع الشطور الضريبية الرسمية لوزارة المالية اللبنانية وقانون الموازنة العامة.",
            "profit": "ضريبة الأرباح",
            "profitIntroTitle": "حاسبة ضريبة الدخل والأرباح",
            "profitIntroBody": "تتيح لك هذه الأداة احتساب ضريبة الدخل والأرباح التجارية والصناعية للمؤسسات الفردية والشركات. تجري الحسابات بناءً على أحدث القوانين النافذة والمحدثة، بناءً على طرق الربح الحقيقي أو المقطوع والشطور التصاعدية المعتمدة قانونياً في لبنان.",
            "penalties": "غرامات التأخير",
            "extensions": "تمديد المهل",
            "reset": "إعادة ضبط",
            "currency": "تحديد عملة الراتب",
            "selectCurrency": "تحديد العملة",
            "lbp": "الليرة اللبنانية (ل.ل)",
            "usd": "الدولار الأمريكي (USD)",
            "salaryPeriod": "دورية الراتب",
            "monthly": "شهري",
            "annual": "سنوي",
            "basicSalaryLbp": "الراتب الشهري الأساسي الخاضع للضريبة (ل.ل)",
            "annualSalaryLbp": "الراتب السنوي الإجمالي (ل.ل)",
            "monthlyUsd": "الراتب الشهري بالدولار (USD)",
            "annualSalaryUsd": "الراتب السنوي بالدولار (USD)",
            "enterSalary": "أدخل الراتب هنا...",
            "enterMonthlySalary": "أدخل الراتب الشهري الحالي...",
            "enterAnnualSalary": "أدخل الراتب السنوي الحالي...",
            "enterExchangeRate": "أدخل سعر الصرف المخصص...",
            "currentValue": "القيمة الحالية:",
            "customRate": "سعر صرف الدولار المخصص (ل.ل مقابل الدولار)",
            "useStandardRate": "استخدم السعر القياسي: 89,500",
            "equivalentLbp": "الراتب الإجمالي بالليرة اللبنانية:",
            "marital": "الوضع العائلي",
            "single": "عازب/ة",
            "spouseWorks": "الزوج/ة (يعمل/تعمل)",
            "spouseDependent": "الزوج/ة (لا يعمل/تعمل)",
            "divorced": "مطلق/ة",
            "widowed": "أرمل/ة",
            "children": "عدد الأولاد",
            "childrenMax": "مؤهل لغاية 5 أولاد كحد أقصى",
            "nssfReg": "خاضع لقانون الضمان الاجتماعي",
            "familyRebates": "تنزيلات عائلية",
            "familyRebatesSub": "تطبيق التنزيلات العائلية (المكلف + الزوج/ة + الأولاد)",
            "annualNssfCeiling": "تحديد سقوف الضمان الاجتماعي سنويًا (اختياري)",
            "annualSicknessCeiling": "سقف المرض والأمومة السنوي",
            "annualFamilyCeiling": "سقف التعويضات العائلية السنوي",
            "optional": "اختياري",
            "calculate": "احتسب",
            "netTakeHome": "صافي الراتب المستلم",
            "complianceSummary": "ملخص الامتثال وجدول الرواتب",
            "netWithFamily": "صافي الراتب المستلم",
            "basedOnEmployee": "بناءً على تفاصيل الموظف",
            "baseMonthly": "الراتب الشهري الأساسي",
            "annualGrossSalary": "الراتب السنوي الإجمالي",
            "grossSalary": "إجمالي الراتب",
            "sicknessNssf": "الضمان الصحي (٣٪ موظف)",
            "mofTax": "ضريبة الدخل التصاعدية",
            "familyAllowances": "التعويضات العائلية المضافة",
            "taxableSalaryAfterRebates": "الراتب الخاضع بعد التنزيلات",
            "totalFamilyRebates": "مجموع التنزيلات العائلية",
            "nssfBranches": "اشتراكات فروع الضمان الاجتماعي (ل.ل)",
            "sicknessBranch": "المرض والأمومة (١١٪)",
            "familyBranch": "التعويضات العائلية (٦٪)",
            "endServiceBranch": "٣. فرع نهاية الخدمة (٨.٥٪)",
            "subjectBase": "الراتب الخاضع:",
            "ceilingLimit": "حد السقف الأقصى:",
            "fullWageNoCeiling": "كامل الراتب (دون سقف)",
            "employeeContribution": "مساهمة المضمون",
            "employerContribution": "مساهمة صاحب العمل",
            "totalNssfEmployer": "ضمان صاحب العمل (22.5%)",
            "employerCostBreakdown": "أعباء ومساهمة أصحاب العمل",
            "lessFamilyAllowances": "يخصم: التعويضات العائلية المضافة",
            "totalCorpCost": "التكلفة الكلية للشركة",
            "warningCount": "1 تحذير امتثال تم اكتشافه",
            "warningDesc": "الراتب الأساسي يقل عما هو مقرر قانوناً كحد أدنى للأجور والبالغ %@ لهذه الفترة.",
            "secureCount": "لم يتم العثور على أخطاء امتثال (0)",
            "secureDesc": "يتوافق هذا الحساب تماماً مع القواعد القياسية لوزارة المالية اللبنانية ومؤسسة الضمان الاجتماعي.",
            "readyTitle": "جاهز لاحتساب الضرائب",
            "readyDesc": "أدخل قيمة الراتب لمشاهدة تفاصيل الضرائب والضمان الاجتماعي.",
            "mofActive": "نشط لدى المالية",
            "annualNetProfit": "صافي الأرباح السنوية الخاضعة للضريبة",
            "enterAnnualNetProfit": "أدخل صافي الأرباح السنوية...",
            "calculateProfit": "إحسب ضريبة الأرباح",
            "profitSummary": "ملخص احتساب ضريبة الأرباح",
            "profitDisclaimer": "تم الاحتساب تلقائياً بموجب جداول المكلفين لضريبة الأرباح الصافية اللبنانية.",
            "totalTaxDue": "إجمالي ضريبة الأرباح المتوجبة",
            "remainingNetProfit": "صافي الأرباح النهائية (بعد تنزيل الضريبة)",
            "rebateHimself": "تنزيل المكلف الأساسي",
            "rebateWife": "تنزيل الزوج/الزوجة",
            "spouseStatusDependent": "لا يعمل/تعمل",
            "spouseStatusWorks": "يعمل/تعمل",
            "rebateChildren": "تنزيل الأولاد",
            "taxableProfitAfterRebates": "الأرباح الخاضعة للضريبة",
            "totalAnnualDeductibleRebate": "إجمالي تنزيل الأرباح السنوية",
            "profitBracketsDetail": "تفاصيل التوزيع على الشرائح التصاعدية",
            "splitWarning": "تنبيه التوزيع: تم مشاركة %50 من تنزيل الأولاد لعمل الزوج/ة",
            "penaltiesIntroTitle": "حاسبة غرامات التأخير والتحصيل",
            "penaltiesIntroBody": "تتيح لك هذه الأداة احتساب غرامات التحقق والتحصيل لجميع أنواع الضرائب (الرواتب، الأرباح، والضريبة المضافة) عند التأخر في تقديم التصاريح أو سداد المبالغ المستحقة بموجب القوانين النافذة.",
            "payrollTax": "ضريبة الرواتب",
            "vatPenalties": "الضريبة المضافة",
            "taxAmount": "قيمة الضريبة (ل.ل)",
            "enterTaxAmount": "أدخل قيمة الضريبة...",
            "zeroTaxNote": "ملاحظة: في حال عدم وجود ضريبة، يجب إدخال صفر لاحتساب الحد الأدنى لغرامة التأخير في التصريح بشكل صحيح.",
            "currentValueLower": "القيمة الحالية:",
            "day": "يوم",
            "month": "الشهر",
            "year": "السنة",
            "profitDueYear": "سنة استحقاق ضريبة الأرباح",
            "paymentDate": "تاريخ الدفع الفعلي / الاحتساب",
            "standardDueDate": "المهلة الرسمية الافتراضية للنظام: %@ (اضغط للتعبئة التلقائية)",
            "calculatePenalties": "احسب الغرامات",
            "totalAmountDue": "إجمالي المبلغ المتوجب",
            "lateMonthsCounted": "%@ شهر تأخير محتسب",
            "minimumVerificationFine": "الحد الأدنى لغرامة التحقق",
            "verificationFine": "غرامة التحقق",
            "collectionFine": "غرامة التحصيل",
            "r5PrincipalTaxPaymentStatus": "حالة دفع أصل ضريبة R5",
            "r5TaxPaidDescription": "الضريبة مدفوعة. تُحتسب غرامة التحصيل (3% شهرياً) حصراً على غرامة التحقق، من دون أصل الضريبة. حتى لو كانت الضريبة مدفوعة، أدخل قيمة الضريبة أعلاه لضمان دقة الاحتساب.",
            "r5TaxUnpaidDescription": "الضريبة غير مدفوعة. يطبّق الاحتساب الحالي غرامة التحصيل على أصل الضريبة وغرامة التحقق.",
            "extensionsIntroTitle": "أداة تتبع تمديد مهل وزارة المالية",
            "extensionsIntroBody": "تتيح لك هذه الأداة مراقبة قرارات تمديد مهل إعداد وتقديم التصاريح الصادرة عن وزارة المالية اللبنانية وحفظها بشكل دائم على الجهاز.",
            "selectExtensionTaxType": "نوع الضريبة المراد تتبع مهلتها:",
            "vat": "الضريبة المضافة",
            "auditReport": "تقرير التدقيق",
            "fiscalYear": "السنة المالية:",
            "filingQuarter": "الفصل المالي (الربع):",
            "primaryStatutoryDueDate": "تاريخ الاستحقاق القانوني الأساسي:",
            "originalDueDate": "تاريخ المهلة الأصلية دون تمديدات",
            "officialExtendedDate": "المهلة الممددة الرسمية الجديدة (أدخل التاريخ الممدد):",
            "saveExtension": "حفظ مهلة التمديد",
            "retrieveExtensions": "استرجاع المهلة الممددة المسجلة",
            "retrieveExtensionsBody": "اضغط على هذا الزر للاستعلام واسترجاع آخر مهلة تمديد قمت بحفظها للأنظمة وبشكل آمن تماماً.",
            "retrieveNow": "استرجاع وعرض المهلة فوراً",
            "retrievedRecord": "النتيجة المسترجعة:",
            "noExtensions": "لا توجد مهل تمديد مسجلة حتى الآن.",
            "companyCategoryProfit": "فئة المكلف بضريبة الأرباح:",
            "companyCategoryAudit": "فئة المكلف لتقرير مفوض المراقبة:",
            "contact": "تم التطوير بواسطة Haddad Audit Firm",
            "contactSub": "مدققون ومشاورون ضريبيون",
            "taxTypeLabel": "نوع الضريبة",
            "companyTaxpayerType": "نوع الشركة / المكلف",
            "companySal": "شركة مساهمة (SAL)",
            "companySarl": "شركة محدودة المسؤولية",
            "companyPartnership": "شركة أشخاص",
            "companyIndividual": "مؤسسة فردية",
            "companyExempt": "مؤسسة مستثناة",
            "companyOther": "مكلفون آخرون",
            "minPrefix": "الحد الأدنى: %@ ل.ل",
            "corporateNote": "تنبيه هام للشركات/شركات الأشخاص: إن غرامة عدم تقديم تقرير مفوض المراقبة هي نفس غرامة عدم تقديم تصريح ضريبة الدخل للشركات/شركات الأشخاص. بناءً عليه، يرجى تحديد المهلة النهائية لتقديم تقرير مفوض المراقبة، بما في ذلك أي تاريخ ممدد، لتبقى غرامة عدم تقديم التقرير متطابقة تماماً مع غرامة عدم تقديم التصريح الضريبي.",
            "fiscalPenaltyAssessment": "بيان غرامات التأخير والمستحقات",
            "legalDueDateRow": "تاريخ الاستحقاق القانوني:",
            "actualPaymentDateRow": "تاريخ السداد الفعلي:",
            "totalDelayPeriod": "مدة التأخير الإجمالية:",
            "monthsSuffix": "شهراً",
            "delayExplain": "فترة التأخير من %@ إلـى %@. كسر الشهر المتبقي اعتبر شهراً قانونياً كاملاً.",
            "noDelayExplain": "تم تسديد الضريبة في المهلة القانونية أو قبلها. لا توجد أي غرامات تأخير مستحقة.",
            "principalTaxAmount": "١. أصل مبلغ الضريبة:",
            "verificationFineMinimum": "غرامة التحقق (الحد الأدنى):",
            "verificationFine5": "غرامة التحقق (٥٪ شهرياً):",
            "verificationFine10": "غرامة التحقق (١٠٪ شهرياً):",
            "collectionFine3": "غرامة التحصيل (٣٪ شهرياً):",
            "collectionFine2": "غرامة التحصيل (٢٪ شهرياً):",
            "grandTotalToRepay": "المجموع الإجمالي والذمة المستحقة للدفع:",
            "principalPlusFines": "(المبلغ الأصلي + الغرامات المترتبة)",
            "compliancePenaltyWarning": "تحذير امتثال: يتم احتساب غرامات التأخير تلقائياً بناءً على قوانين المالية العامة والضرائب المباشرة والرواتب للمرسوم النافذ في الجمهورية اللبنانية.",
            "calculatePenaltiesBtn": "إحسب الغرامات والمستحقات",
            "calculatePayrollTaxes": "إحسب الضرائب والرواتب",
            "calculateProfitTaxBtn": "إحسب ضريبة الأرباح",
            "annualNssfNote": "تنبيه حول السقف السنوي للضمان الاجتماعي: إن السقف السنوي المطبق لكل من فرع التعويضات العائلية وفرع المرض والأمومة يحتسب بضرب السقف الشهري بـ ١٢. في حال حدوث أي تغيير في السقوف خلال السنة، يرجى تعبئة السقوف أعلاه يدوياً.",
            "putRateWarning": "\u{26A0}\u{FE0F} الرجاء إدخال سعر صرف الدولار للمتابعة!",
            "contactHeading": "تفاصيل الاتصال بشركة حداد لتدقيق الحسابات",
            "familyBranchNumbered": "٢. فرع التعويضات العائلية (٦٪)",
            "subjectBaseSickness": "الراتب الخاضع لفرع المرض:",
            "ceilingSickness": "حد السقف الأقصى لفرع المرض:",
            "empContrib3": "مساهمة المضمون (٣٪):",
            "emprContrib8": "مساهمة صاحب العمل (٨٪):",
            "subjectBaseFamily": "الراتب الخاضع لفرع التعويضات:",
            "ceilingFamily": "حد السقف الأقصى لفرع التعويضات:",
            "empContrib0": "مساهمة المضمون (٠٪):",
            "emprContrib6": "مساهمة صاحب العمل (٦٪):",
            "minFloorZero": "تنبيه الحد الأدنى: الضريبة المدخلة هي ٠ ل.ل وهي أقل من الحد الأدنى للفئة (%@). بناءً عليه، حل الحد الأدنى كغرامة تحقق بالكامل، وطبقت غرامة التحصيل على غرامة التحقق (الحد الأدنى).",
            "minFloorBelow": "تنبيه الحد الأدنى: الضريبة المدخلة أقل من الحد الأدنى للفئة (%@). بناءً عليه، حل الحد الأدنى كغرامة تحقق بالكامل، وتحتسب غرامة التحصيل على أصل الضريبة مضافاً إليها غرامة التحقق.",
            "minFloorCalc": "تنبيه الحد الأدنى: غرامة التحقق المحتسبة أقل من الحد الأدنى للفئة (%@). بناءً عليه، حل الحد الأدنى كغرامة تحقق بالكامل، وتحتسب غرامة التحصيل على أصل الضريبة مضافاً إليها غرامة التحقق.",
            "capAlert": "تطبيق حد ١٠٠٪ لغرامة التحقق: غرامة التحقق تجاوزت قيمة أصل الضريبة وتم تخفيضها لتساوي تماماً أصل الضريبة %@ كحد أقصى مسموح به.",
            "emprContrib85": "مساهمة صاحب العمل (٨.٥٪):",
            "payrollCalculateShort": "إحتسب",
            "payrollPlaceholderInfo": "يرجى الضغط على زر 'إحتسب' أعلاه لتوليد تقارير الضرائب والرواتب ومساهمات الضمان الاجتماعي المفصلة.",
            "approxUsdEquivalent": "≈ $%@ USD",
            "yearRestrictionTitle": "تنبيه: قيد السنة",
            "yearRestrictionMessage": "لا يمكنك الرجوع إلى سنة قبل عام ٢٠٢٤. يرجى اختيار سنة ٢٠٢٤ أو ما بعدها.",
            "ok": "موافق",
            "extensionSavedTitle": "تم الحفظ بنجاح",
            "extensionSavedMessage": "تم حفظ تاريخ التمديد الرسمي بنجاح في قاعدة البيانات المحلية.",
            "extensionSameDateTitle": "تنبيه: التاريخ مطابق",
            "extensionSameDateMessage": "تاريخ التمديد المدخل مطابق لتاريخ الاستحقاق القانوني الأساسي (%@). هل تريد المتابعة وحفظه على أي حال؟",
            "cancel": "إلغاء",
            "saveAnyway": "حفظ"
        ]
        return (language == .arabic ? ar[key] : en[key]) ?? key
    }
}
